/** Английские названия тем и разделов туториалов; порядок разделов совпадает с `tutorials` в tutorials.ts. */
export const tutorialsEn: Record<string, { title: string; sections: string[] }> = {
  swift: {
    title: 'Swift',
    sections: [
      'Structs, classes and enums',
      'Properties and property wrappers',
      'Initialization, inheritance and access control',
      'Optional',
      'Errors, defer and control flow',
      'Closures and higher-order functions',
      'Protocols, extensions and type casting',
      'Generics, any / some and type erasure',
      'Dispatch and the Objective-C runtime',
      'Collections, Hashable and complexity',
      'Strings and Unicode',
    ],
  },
  memory: {
    title: 'Memory',
    sections: [
      'App memory: segments and MemoryLayout',
      'Stack and heap',
      'Value and reference types, copying',
      'When a value type ends up on the heap. The existential container',
      'From MRC to ARC: reference counting',
      'Reference types and retain cycles (new version)',
      'ARC under the hood: HeapObject, side table, object lifecycle',
      'Autorelease and autoreleasepool',
      'Memory leaks and memory safety',
    ],
  },
  concurrency: {
    title: 'Concurrency',
    sections: [
      'Concurrency basics',
      'Grand Central Dispatch',
      'Concurrency problems',
      'Thread safety and synchronization',
      'Operation and OperationQueue',
      'Swift Concurrency',
      'RunLoop',
    ],
  },
  architecture: {
    title: 'Architecture and Patterns',
    sections: [
      'Paradigms: OOP, POP, FP',
      'SOLID',
      'KISS, DRY, YAGNI and composition vs inheritance',
      'Creational patterns',
      'Structural patterns',
      'Behavioral patterns',
      'DI, IoC, Service Locator and testability',
      'MVC, MVP, MVVM',
      'VIPER, Clean Swift, MVI',
      'Navigation: Router and Coordinator',
    ],
  },
  uikit: {
    title: 'UIKit',
    sections: [
      'UIView, UIWindow and coordinates',
      'CALayer and rendering',
      'UIViewController and UIView lifecycle',
      'Auto Layout: constraints and anchors',
      'Auto Layout: sizes, priorities, the layout cycle',
      'Touches: UIEvent, UITouch, hitTest',
      'Responder chain, UIControl and gestures',
      'Lists: UIScrollView, UITableView, UICollectionView',
      'Passing data between screens and UIAppearance',
      'UI performance',
      'Layout in code, keyboard, animations, what is new in UIKit',
    ],
  },
};
